### ISSUE TITLE
Poravnava zemljevida v poročilu

### ISSUE THREAD

**Issue by urskabele** [urskabele/APPR-2014-15#5]
Pozdravljeni,

v poročilo v Latexu sem vključila zemljevid, a je zamaknjen preveč na desno. Kako ga lahko poravnam na sredino?

Lp, Urška

**Comment by jaanos** [comment]
Pri vključevanju podaj še širino, npr.
```LaTeX
\includegraphics[width=\textwidth]{../slike/zemljevid.pdf}
```
Če bo zemljevid izgledal premajhen, ga lahko razširiš, a si pri tem pomagaj z ukazom `\makebox`. Namesto širine lahko podaš tudi višino:
```LaTeX
\makebox[\textwidth][c]{
\includegraphics[height=0.7\textheight]{../slike/zemljevid.pdf}
}
```

**Comment by urskabele** [comment]
Sem uredila, hvala.
