### ISSUE TITLE
Končan projekt

### ISSUE THREAD

**Issue by urskabele** [urskabele/APPR-2014-15#6]
Spoštovani,

danes sem končala projekt, ki ga je potrebno še pregledati.

Hvala za pomoč in lep pozdrav,

Urška Bele

**Comment by jaanos** [comment]
Sem dodal povezavo. Mogoče bi ti edino še svetoval, da v poročilo dodaš enačbe za zgrajene linearne in kvadratne modele.

S profesorjem se domeni za termin zagovora. Če boš še kaj spreminjala, odpri nov issue na repozitoriju za zagovore (ali pa ponovno odpri starega).
